# Generated by Django 2.1.1 on 2018-10-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_cgpa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='cgpa',
            new_name='CGPA',
        ),
    ]
