# Generated by Django 2.1.1 on 2018-10-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20181002_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
