# Generated by Django 2.1.1 on 2018-10-02 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentinfo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
