# Generated by Django 2.1.1 on 2018-10-05 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.validator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0007_studentinfo_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='CGPA',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='cgpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='name',
            field=models.CharField(default=2, max_length=120, validators=[students.validator.validate_name]),
            preserve_default=False,
        ),
    ]
