# Generated by Django 2.1.1 on 2018-10-10 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20181006_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='department',
            field=models.CharField(blank=True, default='NOT PROVIDED', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='description',
            field=models.TextField(blank=True, default='NOT PROVIDED', null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='student',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='uid',
            field=models.CharField(default='NOT PROVIDED', max_length=20),
        ),
    ]
